### ISSUE TITLE
The result about the repository.

### ISSUE THREAD

**Issue by iimlearning** [Valentyn1997/semi-supervised-text-classification#1]
hello, thank you for sharing the coding in this repository, and have you ever had a try on some datasets in NLP using this repository? 
Can you share a result on some datasets? 
thank you.

**Comment by iimlearning** [comment]
maybe compare with UDA?

**Comment by Valentyn1997** [comment]
Hi! Sorry for such a delayed answer. 

We discovered that semi-supervised methods, developed for image classification, heavily rely on diverse augmentations. Unfortunately, augmentations for text data don't provide enough inductive bias for semi-supervised text classification.

**Comment by Valentyn1997** [comment]
I added a small section in readme.md with this insight and results for OpenReviews dataset:
<img width="738" alt="image" src="https://user-images.githubusercontent.com/23198776/167655101-63d55858-c5d8-4e98-8a6b-ade0e1741594.png">
